<?php

/**
 * AegisBornCharacterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AegisBornCharacterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AegisBornCharacterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AegisBornCharacter');
    }
}