<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/09 21:37:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cjrgam5_ab',
  'username' => 'cjrgam5_ab',
  'password' => 'user_ab1!',
  'name' => 'doctrine',
)),);
