<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/03 01:10:49
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
  'settings' => 
  array (
    'is_secure' => true,
  ),
  'editemail' => 
  array (
    'is_secure' => true,
  ),
);
