<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/05/09 21:37:06
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
  'settings' => 
  array (
    'is_secure' => true,
  ),
  'editemail' => 
  array (
    'is_secure' => true,
  ),
);
