<?php

/**
 * BaseAegisBornCharacter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $name
 * @property string $sex
 * @property string $class
 * @property integer $level
 * @property integer $position_x
 * @property integer $position_y
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer            getUserId()      Returns the current record's "user_id" value
 * @method string             getName()        Returns the current record's "name" value
 * @method string             getSex()         Returns the current record's "sex" value
 * @method string             getClass()       Returns the current record's "class" value
 * @method integer            getLevel()       Returns the current record's "level" value
 * @method integer            getPositionX()   Returns the current record's "position_x" value
 * @method integer            getPositionY()   Returns the current record's "position_y" value
 * @method sfGuardUser        getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method AegisBornCharacter setUserId()      Sets the current record's "user_id" value
 * @method AegisBornCharacter setName()        Sets the current record's "name" value
 * @method AegisBornCharacter setSex()         Sets the current record's "sex" value
 * @method AegisBornCharacter setClass()       Sets the current record's "class" value
 * @method AegisBornCharacter setLevel()       Sets the current record's "level" value
 * @method AegisBornCharacter setPositionX()   Sets the current record's "position_x" value
 * @method AegisBornCharacter setPositionY()   Sets the current record's "position_y" value
 * @method AegisBornCharacter setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    AegisBorn
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAegisBornCharacter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aegis_born_character');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('sex', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('class', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('position_x', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('position_y', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}